### PR TITLE
adding jade templates & styling etc

### PR DESCRIPTION
**Pull request by letspresto**
@orz-orz-orz-orz-orz please look at these additions. Afraid some stuff might break...

### CODE REVIEW

**Comment by letspresto** [comment]
Once I know these won't break and you can render a template from the index.js file then i'll continue with the front-end

**Comment by letspresto** [comment]
Also, just highlighting the following dependencies are needed:

"jade": "*"
"method-override": "*"
"morgan": "*"
"serve-favicon": "*"

**Comment by orz-orz-orz-orz-orz** [comment]
installed packages

**Comment by letspresto** [comment]
Look at most recent commit. I'll email you a gif on how it would function. Could you follow the style for querying messages on the database on your end and add to the index.js file?

**Comment by orz-orz-orz-orz-orz** [comment]
merged

http://104.131.5.90:5000/

**Pull request merged**
